remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: "MSc Data Science e-Portfolio"

# Custom navigation menu
menu:
  - text: "Home"
    link: "/"
  - text: "Deciphering Big Data"
    link: "/Deciphering_Big_Data/README.md"
