# Remote theme from Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-github-metadata
  - jekyll-include-cache

# Site title and description
title: "MSc Data Science e-Portfolio"
description: "A professional collection of my work, reflections, and development throughout my MSc in Data Science."

# Site-wide navigation settings
header:
  title: "MSc Data Science e-Portfolio"
  tagline: "Reflecting on Learning and Development"
  logo: "/assets/images/logo.png"  # Ensure this path is correct, or remove if no logo

# Navigation bar
navigation:
  - title: "About Me"
    url: "/about-me/"
  - title: "Modules"
    children:
      - title: "Deciphering Big Data"
        url: "/deciphering-big-data/"
      - title: "Machine Learning"
        url: "/machine-learning/"
      - title: "Research Methods and Professional Practice"
        url: "/research-methods/"
  - title: "Professional Development"
    url: "/professional-development/"
  - title: "Contact"
    url: "/contact/"

# Footer links
footer:
  links:
    - title: "GitHub"
      url: "https://github.com/reece-lance"
    - title: "LinkedIn"
      url: "https://www.linkedin.com/in/reece-lance"

# Author details
author:
  name: "Reece Lance"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/reece-lance"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/reece-lance"

# Optional site-wide settings
show_excerpts: true
