# Remote theme from Minimal Mistakes
remote_theme: andrewbanchich/forty-jekyll-theme
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-github-metadata
  - jekyll-include-cache

# Site title and description
title: "MSc Data Science e-Portfolio"
description: "A professional collection of my work, reflections, and development throughout my MSc in Data Science."

# Site-wide navigation settings
header:
  title: "MSc Data Science e-Portfolio"
  navigation: true
  tagline: "Reflecting on Learning and Development"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

author:
  name: "Reece Lance"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/reece-lance"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/reece-lance"

footer:
  social_links:
    - title: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/reece-lance"
    - title: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/reece-lance"
    - title: "Contact Me"
      icon: "fas fa-envelope"
      url: "/contact/contact.md"

# Optional site-wide settings
show_excerpts: true
